name: knowledge-commons-idms

services:
  comanage:
    type: lando
    app_mount: disabled
    ssl: true
    run_as_root:
      - cd /var/cache/registry && rm -r *
    services:
      build:
        context: ./services/comanage
        dockerfile: Dockerfile
      command: "docker-comanage-entrypoint apache2-foreground"
      ports:
        - 80
        - 443
    overrides:
      volumes:
        - ./services/comanage/local:/srv/comanage-registry/local
        - ./services/comanage/plugins:/srv/comanage-registry/plugins
        - ./services/comanage/cache:/var/cache/registry
      environment:
        - COMANAGE_DB_HOST=comanage-db
        - COMANAGE_DB_USER=registry
        - COMANAGE_DB_PASSWORD=registry
        - COMANAGE_DB_NAME=registry
        - COMANAGE_REGISTRY_ADMIN_GIVEN_NAME=Admin
        - COMANAGE_REGISTRY_ADMIN_FAMILY_NAME=Local
        - COMANAGE_REGISTRY_ADMIN_USERNAME=admin
        - COMANAGE_EMAIL_FROM=admin@lndo.site
        - COMANAGE_EMAIL_HOST=mailhog
        - COMANAGE_EMAIL_PORT=1025
        - COMANAGE_EMAIL_USERNAME=
        - COMANAGE_EMAIL_PASSWORD=
  comanage-db:
    type: mariadb
    creds:
      user: registry
      password: registry
      database: registry
    healthcheck: false
    portforward: true
  discovery:
    type: php:8.2
    webroot: services/discovery/web
    via: nginx
    ssl: true
  playwright:
    type: node:23
    build_as_root:
      - cd /app/playwright && npm install && npx playwright install --with-deps
    overrides:
      environment:
        - PLAYWRIGHT_BROWSERS_PATH=/app/playwright/browser-cache
  sp:
    type: php:8.2
    webroot: services/local-sp/web
    via: nginx
    ssl: true
    config:
      vhosts: services/local-sp/lando/nginx.conf
    overrides:
      environment:
        - SIMPLESAMLPHP_CONFIG_DIR=/app/services/local-sp/config
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - comanage

proxy:
  sp_nginx:
    - sp.lndo.site
  discovery_nginx:
    - discovery.lndo.site
  comanage:
    - comanage.lndo.site

tooling:
  run-tests:
    service: playwright
    description: Runs playwright tests
    dir: /app/playwright
    cmd: npx playwright test --reporter=line
  comanage-mysql:
    service: comanage-db
    description: Connects to the comanage database
    cmd: mysql -u registry -pregistry registry
  comanage-db-export:
    service: comanage-db
    dir: /app/services/comanage
    description: Exports the comanage database
    cmd: mysqldump -u registry -pregistry registry > registry.sql
  comanage-db-import:
    service: comanage-db
    dir: /app/services/comanage
    description: Imports the comanage database
    cmd: mysql -u registry -pregistry registry < registry.sql
