<script type="text/javascript">
$('body').addClass('info-page');
</script>
<header><h1 class="entry-title ">About <em>Humanities Commons</em></h1></header>
<h4>NOTE: This Service Provider is the registry service for <strong><em>Humanities Commons</em></strong>. Both services respect the Research & Scholarship Category (R&S) requirements.</h4>
<div class="entry-content">
<p><em>Humanities Commons</em> is a trusted, nonprofit network where humanities scholars can create a professional profile, discuss common interests, develop new publications, and share their work. The <em>Humanities Commons</em> network is open to anyone.</p><p><em>Humanities Commons</em> is a project of the office of scholarly communication at the Modern Language Association. Its development was generously funded by a <a href="https://mellon.org/grants/grants-database/grants/modern-language-association-of-america/21700693/" target="_blank" rel="noopener noreferrer">grant from the Andrew W. Mellon Foundation</a>. <em>Humanities Commons</em> is based on the open-source <a href="http://commonsinabox.org/">Commons-in-a-Box</a> project of the <a href="http://www2.cuny.edu/">City University of New York</a> and the <a href="http://www.gc.cuny.edu/Home">CUNY Graduate Center</a> and is an expansion of the MLA's <em>MLA Commons,</em> which launched in January 2013. The <a href="https://hcommons.org/societies">founding partner societies</a> of <em>Humanities Commons</em> are the Association for Jewish Studies; the Association for Slavic, East European, and Eurasian Studies; and the College Art Association. Each society has its own <em>Commons</em> hub.</p><p><em>Humanities Commons</em> was designed by scholarly societies in the humanities to serve the needs of humanists as they engage in teaching and research that benefit the larger community. Unlike other social and academic communities, <i>Humanities Commons</i> is open-access, open-source, and nonprofit. It is focused on providing a space to discuss, share, and store cutting-edge research and innovative pedagogy—not on generating profits from users' intellectual and personal data.</p><p>The network also features an open-access repository, the <a href="https://hcommons.org/core"><em>Commons Open Repository Exchange</em></a>. <em>CORE</em> allows users to preserve their research and increase its reach by sharing it across disciplinary, institutional, and geographic boundaries. <a href="https://hcommons.org/core/press-release/">Developed in partnership</a> with Columbia University's <a href="http://cdrs.columbia.edu/cdrsmain/">Center for Digital Research and Scholarship</a>, <em>CORE</em> is underwritten by a <a href="https://news.mla.hcommons.org/2016/08/09/humanities-core-receives-neh-grant/">grant from the National Endowment for the Humanities' Office of Digital Humanities</a>.</p>
</div>

